### ISSUE TITLE
Add multiple grids to a single map.

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/caac-map#11]
To replicate Chelsea's complete design.

Do we need to do this from the server?

**Comment by chadwhitacre** [comment]
I think we should, yes. I think we should generate one SVG document.

![screen shot 2015-07-10 at 5 20 30 pm](https://cloud.githubusercontent.com/assets/134455/8629295/fe9c3b12-2727-11e5-8827-b35e9d50cee5.png)

**Comment by chadwhitacre** [comment]
We noted at some point earlier that the block pattern (zoomed-out scale) is approximately fractal with the building pattern (zoomed-in scale). Here are the differences I'm seeing:
- The streets are wider relative to the blocks than the alleys are to the buildings.
- The city as a whole doesn't fit neatly within a quadrilateral (or ell).

| part | separator | represents |
| :-- | :-- | :-- |
| city |  | a local learning community |
| block | street | topic area |
| building | alley | resource |

There are 17 pieces on the sketch above. We currently have [five topic areas](https://docs.google.com/spreadsheets/d/1wZ2uz0KTkylLgo46fJ7gYYpNEKjVljoGTCjFecjZQ9c/edit?usp=sharing).

**Comment by chadwhitacre** [comment]
Chatted with @timothyfcook about this here at the Sprout office. We're going to assume that at the city level we're dealing with a square, which means we can follow the same basic algorithm as we do at the block level. We should be able to run once to produce a map with five (seven) shapes, and then iterate over those seven shapes and fill each with an additional run of the algorithm.

**Comment by chadwhitacre** [comment]
First step is to get a nested map in Python-space, then after that we'll figure out how to dump it out to SVG.

**Comment by timothyfcook** [comment]
We can finish this by:
- [x] fixing the individual maps (still broken)
- [x] printing the .svg as a collective map (with 5 smaller grids within it)

**Comment by chadwhitacre** [comment]
Labeling this `High Priority`, yes @timothyfcook?

**Comment by timothyfcook** [comment]
Yessir

**Comment by chadwhitacre** [comment]
Reopening to tweak to @timothyfcook's satisfaction.
