### ISSUE TITLE
add circle targets

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/caac-map#13]
Does it make sense to do this in genmap or at the js layer?

**Comment by chadwhitacre** [comment]
Design calls for circle targets in the middle of each piece:

![screen shot 2015-07-10 at 5 13 36 pm](https://cloud.githubusercontent.com/assets/134455/8629206/2ce6849c-2727-11e5-99ab-fe808a2a2f61.png)

**Comment by chadwhitacre** [comment]
Note the circles are supposed to change with shape states:

![screen shot 2015-07-10 at 5 17 59 pm](https://cloud.githubusercontent.com/assets/134455/8629260/a9bea42c-2727-11e5-810d-7f7ce89ca342.png)

**Comment by timothyfcook** [comment]
@cameronscott137 can do this with styling after genmap is run

**Comment by cameronscott137** [comment]
To clarify, this will need to happen predominantly in the JS layer, with a maybe a bit of CSS overtop. Contingent on getting #19 worked out first.

**Comment by timothyfcook** [comment]
You might be able to visually add the circle nodes prior to have the pathway logic working.

**Comment by cameronscott137** [comment]
I can do hollow circles that fill in on hover/click, but otherwise, the
circles won't mean much without the pathways running between them. Let me
know.

On Tue, Aug 4, 2015 at 9:20 AM, Tim Cook notifications@github.com wrote:

> You might be able to visually add the circle nodes prior to have the
> pathway logic working.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/caac-map/issues/13#issuecomment-127607022.

## 

Cameron
(610) 883-7342

**Comment by timothyfcook** [comment]
Up to you. I can't imagine any dependency on the pathways logic/viz, but there could be.

I'd say the on:hover fill/coloring should be lumped in with the hover:over for the brick itself. Although it would be visually interesting in the node-circle was a different color than the brick.

**Comment by chadwhitacre** [comment]
What's left on this ticket, @timothyfcook? Current status:

![screen shot 2015-09-11 at 8 42 39 am](https://cloud.githubusercontent.com/assets/134455/9815064/4e9305b4-5861-11e5-9a75-9262c7d6c018.png)

**Comment by timothyfcook** [comment]
Fine here. But there are subsequent tickets for #56 etc.
