### ISSUE TITLE
add zooming UI

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/caac-map#24]
Once we have a larger map we need to be able to navigate. Probably just a zooming/scrolling UI should work.

**Comment by cameronscott137** [comment]
Possible to do with jQuery, I think, but it'll be an adventure. Need to hold until we have multiple maps.

**Comment by timothyfcook** [comment]
@MatthewVita this is all yours now!

**Comment by timothyfcook** [comment]
make our map with a navigation interface more like google maps.

**Comment by chadwhitacre** [comment]
Started a PR in #203.

**Comment by chadwhitacre** [comment]
Erm ... https://github.com/saxifrage/cityasacampus/pull/203 (another reason to ticket things in the proper repo ;).

**Comment by MatthewVita** [comment]
oops, I forgot about this one. Reassigned back to Chad since he finished it.

I like the svg transform approach you took. Very clean.
