### ISSUE TITLE
clean up browsing UI for hovers/links

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/caac-map#25]
Currently: tooltips have just text linked to outside site
Should be: both bricks and tooltips have links to open the card; link to outside site is only accessed through card.

**Comment by timothyfcook** [comment]
I think the click to bring up the card should only be tied to the brick, the tooltip could be more opaque as just a reference, but doesn't have any links in it that pull up cards.

that way if a tooltip is covering an adjacent brick it doesn't get in the way of clicking on that brick.

or the tooltip should just go away when you leave the brick area. right now if your cursor is ON the tooltip it stays up even if you leave the brick area.

**Comment by chadwhitacre** [comment]
This ticket is old and in the way.
