### ISSUE TITLE
tooltips should go away when you leave a grid

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/caac-map#27]
the last brick you hovered-over leaves its tool tip up once even after you leave the grid.

**Comment by cameronscott137** [comment]
Tooltips now disappear if a user hovers off the map , or clicks off the corresponding rectangle.

https://github.com/saxifrage/learn/commit/93db0c40f72802f0617b36bb8d3eb7e79db175dc

**Comment by timothyfcook** [comment]
are these changes live on http://cityasacampus.org/map/ ? I'm still seeing the tooltip

**Comment by timothyfcook** [comment]
Right now tooltips go away if your mouse leaves the browser window, but not if it leaves the grid.

It needs to be something like:

IF hover:over NOT on a brick, THEN hide any tool-tips.

**Comment by cameronscott137** [comment]
Okay, sounds like you and I are seeing different things. Will reconcile
today.

On Tue, Aug 4, 2015 at 9:13 AM, Tim Cook notifications@github.com wrote:

> Right now tooltips go away if your mouse leaves the browser window, but
> not if it leaves the grid.
> 
> It needs to be something like:
> 
> IF hover:over NOT on a brick, THEN hide any tool-tips.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/caac-map/issues/27#issuecomment-127601965.

## 

Cameron
(610) 883-7342

**Comment by timothyfcook** [comment]
Ah. I figured it out. Technically it _does_ go away when you leave the "grid", its just that the grid object includes all of the whitespace in the square canvas that is wrapped around the grid. The tooltips go away when you further to the side and fully leave that invisibly bounded square grid area.

Is there a way to isolate the grid itself as an object inside of the square grid canvas?

**Comment by cameronscott137** [comment]
Yeah, its a weird byproduct of the transform that's on the <svg> element. I
can see if I can't target it specifically to the <g> element that groups
all the <rect> elements together.

On Tue, Aug 4, 2015 at 4:29 PM, Tim Cook notifications@github.com wrote:

> Ah. I figured it out. Technically it _does_ go away when you leave the
> "grid", its just that the grid object includes all of the whitespace in the
> square canvas that is wrapped around the grid. The tooltips go away when
> you further to the side and fully leave that invisibly bounded square grid
> area.
> 
> Is there a way to isolate the grid itself as an object inside of the
> square grid canvas?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/caac-map/issues/27#issuecomment-127749997.

## 

Cameron
(610) 883-7342

**Comment by timothyfcook** [comment]
Cool, yeah. This might be less of an issue when we finish #11 and have more grids on the map since the transform and the extra white space will just be around the edge of the total map, not around each grid.

**Comment by chadwhitacre** [comment]
I think I'm not seeing this anymore. Reopen if you do.
