### ISSUE TITLE
tooltip should be disabled when card open

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/caac-map#30]
so you don't get overlap:

![screen shot 2015-07-31 at 12 45 43 pm](https://cloud.githubusercontent.com/assets/1823300/9012410/8081ba8e-3782-11e5-9ee1-1e89ac97ed90.png)

**Comment by cameronscott137** [comment]
Seems like I should just able able to do:

https://gist.github.com/cameronscott137/6704d2b1268b443654a7

That doesn't seem to be doing the trick, though. @whit537 Could I ask you to jump in here?

**Comment by chadwhitacre** [comment]
This went away when we moved cards to flyouts.
