### ISSUE TITLE
Build directional logic so that popover stays on the screen

### ISSUE THREAD

**Issue by cameronscott137** [saxifrage/caac-map#34]
From @timothyfcook:  Set rules so that entire box appears on screen (in some cases, clicking on box made it appear 80% off screen forcing a scroll down ) --- this might be tricky.

**Comment by cameronscott137** [comment]
Since we no longer have popovers, I believe this issue is no longer relevant. @timothyfcook, confirm?

**Comment by timothyfcook** [comment]
yessir! excellent.
