### ISSUE TITLE
Tooltip comes back on if you re-hover:over

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/caac-map#39]
Tooltip goes away if you click on brick and bring up card, but then if you hover:over again, the tooltip returns and is blocked by the card.
![screen shot 2015-08-04 at 4 22 12 pm](https://cloud.githubusercontent.com/assets/1823300/9071756/1ffae352-3ac5-11e5-94df-5f3a229107c8.png)

**Comment by cameronscott137** [comment]
Already have this logged under #30

**Comment by timothyfcook** [comment]
Cool. Sorry, thought you closed it because it is improved... just not all the way there.
