### ISSUE TITLE
Setup a Django DB and input form for new data and data validation

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/caac-map#47]

**Comment by timothyfcook** [comment]
Or, instead, we could just use the Admin Area of the CaaC project. Unless we want people to just be able to generate their own maps... which we do.

So maybe it's a both-and. We have one instance of the CaaC-map that is for the larger CaaC project and then we have a stand-alone map project that uses it's own simple DB and input UI.

**Comment by chadwhitacre** [comment]
> [W]e could just use the Admin Area of the CaaC project.

This is the direction we're going.
