### ISSUE TITLE
Certain cards cover too much of the map

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/caac-map#59]
![screen shot 2015-09-08 at 8 44 53 am](https://cloud.githubusercontent.com/assets/1823300/9735148/aecfd46e-5606-11e5-9a96-6422845db9aa.png)

Not sure what a good solution is. 

Either we could have the cards default to the side of the map where they cover the least. or we could change it so that the card view is stuck on the side of the map, instead of of acting like a giant tooltip.

**Comment by timothyfcook** [comment]
Or maybe it's OK as is. @chelseaerdner what are your thoughts?

**Comment by chelseaerdner** [comment]
I say that we only allow for a certain character limit in the description and then provide a text link that says "read more" to would expand the rest. But on initial display, it would be condensed to three lines. It wouldn't link out to another page or anything. Just expand the text to this view but the user would have to initiate it.

**Comment by timothyfcook** [comment]
So show the image box, maybe 2 lines of text, and a "Read More" button" that accordions out the rest of the card within the same pageview.

That could work. 

You don't like the "move the 'card' to the margins" idea? ...where we would have the same card layout but just stuck on the right side.

**Comment by chelseaerdner** [comment]
I'd have to see it in action but I am hesitant to take that approach because it separates the card from the path and disconnects it to the nod. I think the smaller cards would get lost pinned right and I wouldn't want to bounce back and fourth between cards pinned to the nod and then pinned to the right. Just my thoughts.

**Comment by timothyfcook** [comment]
Chad and I are talking about this IRL as it relates to a clear view of the pathways a la #61 

@chelseaerdner can you solve for this UI problem? We're thinking maybe the resource card could become a modal so interactions with it are separated from the map.

The cards just cover too much of the map.

![img_0307](https://cloud.githubusercontent.com/assets/1823300/9968773/55c15f90-5e18-11e5-880b-2ccb50ed736e.JPG)

**Comment by chelseaerdner** [comment]
Sure, let me see what I can come up with. Ill have something over to you by Monday. I am planning on finishing up the homepage wireframes too so you can expect both of those!

It seems to be the best solution but we can discuss in detail once we see it come together.

**Comment by chelseaerdner** [comment]
@timothyfcook, this is what your sketch option would look like for the cards. I think it works well. The user can participate, click on the next nod in the path, or close the modal and leave where they left off. I think the dark overlay should take up the whole screen and each card should display centered on the screen. All cards should stay consistent with centered placement. 

Thoughts?

![popup_09212015](https://cloud.githubusercontent.com/assets/11842603/9997357/c9293ca8-6059-11e5-9291-662015050625.png)

**Comment by chadwhitacre** [comment]
For reference, Google Maps has their card equivalent off to the side:

![screen shot 2015-10-23 at 3 40 37 pm](https://cloud.githubusercontent.com/assets/134455/10703305/19a8825e-799d-11e5-9999-c67bf4ab8859.png)
![screen shot 2015-10-23 at 3 40 44 pm](https://cloud.githubusercontent.com/assets/134455/10703306/19af95e4-799d-11e5-9f6d-12addf4e94b6.png)

**Comment by cameronscott137** [comment]
@timothyfcook: I like this approach much better. Can implement this weekend.

On Fri, Oct 23, 2015 at 3:45 PM, Chad Whitacre notifications@github.com
wrote:

> For reference, Google Maps has their card equivalent off to the side:
> 
> [image: screen shot 2015-10-23 at 3 40 37 pm]
> https://cloud.githubusercontent.com/assets/134455/10703305/19a8825e-799d-11e5-9999-c67bf4ab8859.png
> [image: screen shot 2015-10-23 at 3 40 44 pm]
> https://cloud.githubusercontent.com/assets/134455/10703306/19af95e4-799d-11e5-9f6d-12addf4e94b6.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saxifrage/caac-map/issues/59#issuecomment-150673009.

## 

Cameron
(610) 883-7342

**Comment by timothyfcook** [comment]
@cameronscott137 awesome this is a high priority interaction improvement before our Wednesday pitch meeting.

I like it. Let's go with the design above by @chelseaerdner but align-left-center. Except not in a modal so you can still interact with the map.

So the interaction then is:
- Hover-over and see tooltips
- Click tooltip to bring up card on left
- Click on other nodes in map to change cards
  - OR click on little pathway bar in card to change cards (let's make it a bit bigger with hover-overs on the little nodes to imply interaction)
- Click "X" in top-right corner of card to remove card and resume map-only view

**Comment by cameronscott137** [comment]
@whit537, I've been out of the map for a few weeks. Is the best course of action to pull this down and generate the map? Or to use the version living over in the `gh-pages` branch of the other repo?

**Comment by chadwhitacre** [comment]
@cameronscott137 `gh-pages` in the other repo. All of these UI tickets should be over in that repo (@timothyfcook created them in the wrong repo).

**Comment by cameronscott137** [comment]
@whit537 Thanks!

Initial migration of popovers to flyout menu is live via f1434fcb01ac0d38e7091f9a2c0dcdcf2fe6eadd.

![screen shot 2015-10-25 at 10 14 15 am](https://cloud.githubusercontent.com/assets/2473472/10716048/3a0fa4cc-7b01-11e5-935e-efbeeedcd35b.png)

Later today, will better space flyout content and add transitions when the flyout enters/exits.

**Comment by cameronscott137** [comment]
The other thing to consider is that, without the popover pointing directly at it, a user no longer knows which map cell is currently being referenced. We should explore a different color cue for an "active" cell.

**Comment by timothyfcook** [comment]
Agreed. Definitely another color for the active cell. Something green!

Would be nice to get that pathways graphic on top of the card as well like Chelsea had in her recent mockup.

**Comment by cameronscott137** [comment]
Okay, bunch of improvements just pushed:
- To differentiate from other cells in the path, clicked-on cell now turn green. Will left @chelseaerdner tell me what specific shade.
- Flyout menu now has a close function in the "X" at top right. When hit, the flyout slides off-canvas, and the map is cleared of paths.
- Transitions everywhere! The flyout slides in and out, and the map cells now transition between colors.

**Comment by cameronscott137** [comment]
@timothyfcook, will work on the pathways graphic, but will definitely take a bit of time to work through, and strikes me that there are other issues more pressing to fix between now and Wednesday?

**Comment by cameronscott137** [comment]
Per @chelseaerdner's suggestion, could also try a gentle pulsing instead of an outright color change. Makes it feel more "active." Just pushed the change, check it aht: http://cityasacampus.org/map/

**Comment by timothyfcook** [comment]
Definitely.

Getting the home page up is a big priority. 

Then there’s lots of work to do to start building out a nicer UI for the admin dashboard pages.

**Comment by timothyfcook** [comment]
@cameronscott137 looks good! Only thing left to close out this ticket completely would be to make it so that the map re-centers on the chosen tile. If you choose a tile on the left side of the map it gets covered by the card.

**Comment by timothyfcook** [comment]
This is related to #46 ...can maybe solve for both at once.

**Comment by cameronscott137** [comment]
Okay. God willing, I think I can do this with a little js plugin.

**Comment by chadwhitacre** [comment]
... and the creek don't rise! I'm around today if you need a hand with that, @cameronscott137. Looks great so far!

**Comment by chadwhitacre** [comment]
Centering on card load reticketed as https://github.com/saxifrage/cityasacampus/issues/330. Closing.
