### ISSUE TITLE
Hover-over highlighting does not work for pathway colors

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/caac-map#60]
The darker colors of the pathway blocks don't allow hover-overs to do anything. Seems like if we shift the color scheme at large to echo Chelsea's design, then the really dark blue could be used for all hover-overs.

The ultra-light blue is the non-highlighted color, and the middle blue is the default color.

![screen shot 2015-09-04 at 11 41 13 am](https://cloud.githubusercontent.com/assets/1823300/9735216/2ee544c2-5607-11e5-93e3-9ab227ed479a.png)

**Comment by cameronscott137** [comment]
Done, son. @timothyfcook, feel free to verify and close if good.

**Comment by timothyfcook** [comment]
:+1:
