### ISSUE TITLE
set up DNS

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/caac-map#74]
@timothyfcook is buying `caac-map.net` as we speak! :dancer:

**Comment by chadwhitacre** [comment]
And the IP address is ... !

**Comment by chadwhitacre** [comment]
159.203.131.86

**Comment by timothyfcook** [comment]
created! but propagated? TTL 3600!

**Comment by chadwhitacre** [comment]
Got it! Thanks! :-)
